RUBY/RAILS/activites/cours_2/activite_1/adlibitum/config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#index'

  get 'advertisements/login' => 'users#login'
  patch 'advertisements/:id' => 'advertisements#publish'
  post 'advertisements/:id' => 'comments#create'
  post 'advertisements/login' => 'users#check'

  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  delete 'users' => 'users#logout'

  resources :comments
  resources :advertisements
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/models/user.rb
class User < ApplicationRecord
  has_many :comments

  validates :name, presence: {
    notice: 'Name is required'
  }

  validates :password, presence: {
    notice: 'Password is required'
  }

  validates :name, uniqueness: {
    notice: 'Already taken'
  }

  def admin?
    role == 'admin'
  end
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users
  # GET /users.json
  def index
    if !@current_user.try(:admin?)
      flash[:notice] = 'Forbidden'
      redirect_to request.referrer || root_path
    else
      @users = User.all
   end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    index
    @users = nil
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    show
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.role = 'user'

    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login; end

  def logout
    session[:user_id] = nil
    flash[:info] = 'You are now logged out'
    redirect_to advertisements_path
  end

  def check
    @current_user = User.where(name: params[:name], password: params[:password]).first
    if @current_user
      session[:user_id] = @current_user.id
      flash[:notice] = 'Welcome !'
      redirect_to advertisements_path
    else
      session[:user_id] = nil
      flash[:notice] = 'Login error'
      redirect_to users_login_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :password, :role)
  end
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/helpers/users_helper.rb
module UsersHelper
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/_login_form.html.erb
<% if @current_user %>
	<% if @current_user.try(:admin?) %>
		<b>Administrator <%= "'#{@current_user.name}'" %></b>
	<% else %>
		<b><%= "'#{@current_user.name}'" %></b>
	<% end %>
	<%= form_tag users_path, method: :delete do %>
		<%= submit_tag('Logout') %>
	<% end %>
<% else %>
	<b>Anonymous</b>
	<%= link_to 'Login', users_login_path %>
	<%= link_to 'Sign up', new_user_path %>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/edit.html.erb
<%= render 'users/login_form' %>

<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/home.html.erb
<% if @current_user %>
	<% if @current_user.role == 'admin' %>
	<h1>Bienvenue administrateur <%= @current_user.name %></h1>
	<% else %>
	<h1>Bienvenue <%= @current_user.name %></h1>
	<% end %>
<%= form_tag users_path, method: :delete do %>
	<%= submit_tag('Se déconnecter') %>
	<% end %>
<% else %>
	<h1>Bienvenue visiteur anonyme :)</h1>
	<%= link_to "S'identifier", users_login_path %>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/index.html.erb
<%= render 'users/login_form' %>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/login.html.erb
<h1>Login</h1>

<%= form_tag "/users/login", method: :post do %>
	<%= label_tag(:name, 'Name') %>
	<%= text_field_tag (:name), nil, autofocus: true, required: true %>
	<%= label_tag(:password, 'Password') %>
	<%= password_field_tag (:password), nil, required: true %>
	<%= submit_tag('Login') %>
<% end %>

<%= link_to 'Back', request.referrer || root_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', try(request.referrer) || root_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/users/show.html.erb
<%= render 'users/login_form' %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>