RUBY/RAILS/activites/cours_2/activite_1/adlibitum/config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#index'

  get 'advertisements/login' => 'users#login'
  patch 'advertisements/:id' => 'advertisements#publish'
  post 'advertisements/:id' => 'comments#create'
  post 'advertisements/login' => 'users#check'

  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  delete 'users' => 'users#logout'

  resources :comments
  resources :advertisements
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/models/advertisement.rb
class Advertisement < ApplicationRecord
  belongs_to :user
  has_many :comments

  validates :title, presence: {
    notice: 'Your ad needs a title'
  }

  validates :title, uniqueness: {
    notice: 'Already posted'
  }

  validates :content, presence: {
    notice: 'A content is required'
  }

  validates :price, presence: {
    notice: 'We cannot guess a price for you'
  }

  validates :price, numericality: true

  scope :published, (-> { where(state: 'published') })
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :set_advertisement, only: %i[show edit update destroy]

  # GET /advertisements
  # GET /advertisements.json
  def index
    @advertisements = if @current_user.try(:admin?)
                        Advertisement.all
                      else
                        Advertisement.published
                      end
  end

  # GET /advertisements/1
  # GET /advertisements/1.json
  def show
    # si l'utilisateur connecte n'est pas admin et si l'annonce n'est pas publiee
    # (non j'ai essaye le Advertisement.published et ici il ne donne rien)
    if !@current_user.try(:admin?) && @advertisement.state != 'published'
      flash[:notice] = 'Forbidden'
      redirect_to request.referrer || root_path
    end
    # pour ne garder que les commentaires de l'annonce en cours, dans l'ordre inverse
    @comments = Comment.all.reverse.select { |c| c.advertisement_id == @advertisement.id }
  end

  # GET /advertisements/new
  def new
    @advertisement = Advertisement.new
    @advertisement.user_id = @current_user.id
    @advertisement.state = 'waiting'
  end

  # GET /advertisements/1/edit
  def edit; end

  # POST /advertisements
  # POST /advertisements.json
  def create
    @advertisement = Advertisement.new(advertisement_params)

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to request.referrer || root_path, notice: 'Advertisement was successfully created.' }
        format.json { render :show, status: :created, location: @advertisement }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /advertisements/1
  # PATCH/PUT /advertisements/1.json
  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to @advertisement, notice: 'Advertisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advertisement }
      else
        format.html { render :edit }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /advertisements/1
  # DELETE /advertisements/1.json
  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to advertisements_url, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def publish
    Advertisement.find(params[:id]).update state: 'published'
    redirect_to advertisements_path
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_advertisement
    @advertisement = Advertisement.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def advertisement_params
    params.require(:advertisement).permit(:title, :content, :state, :price, :user_id)
  end
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/advertisements/_form.html.erb
<%= form_with(model: advertisement, local: true) do |form| %>
  <% if advertisement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advertisement.errors.count, "error") %> prohibited this advertisement from being saved:</h2>

      <ul>
      <% advertisement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :advertisement_title, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :advertisement_content, size: "90x10" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :advertisement_price %>
  </div>

  <div class="actions">
	  <%= form.submit %>
  </div>

<!-- HIDDEN -->
  <div class="field">
	  <%= form.hidden_field :state, id: :advertisement_state %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, id: :advertisement_user_id %>
  </div>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/advertisements/edit.html.erb
<%= render 'users/login_form' %>

<h1>Editing Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/advertisements/index.html.erb
<%= render 'users/login_form' %>

<br><br>
<h1>Advertisements</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>State</th>
      <th>Price</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @advertisements.each do |advertisement| %>
      <tr>
        <td><%= advertisement.title %></td>
        <td><%= advertisement.content %></td>
        <td><%= advertisement.state %></td>
        <td><%= advertisement.price %></td>
        <td><%= advertisement.user.name %></td>
        <td><%= link_to 'Show', advertisement %></td>
		  <% if @current_user.try(:id) == advertisement.user_id %>
		    <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
		  <% elsif @current_user.try(:admin?) %>
          <td><%= link_to 'Edit', edit_advertisement_path(advertisement) %></td>
          <td><%= link_to 'Destroy', advertisement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			 <% unless advertisement.state == 'published' %>
			   <td><%= link_to 'Publish', advertisement, method: :patch %></td>
			 <% end %>
		  <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if @current_user %>
<%= link_to 'New Advertisement', new_advertisement_path %>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/advertisements/new.html.erb
<h1>New Advertisement</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Back', advertisements_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/advertisements/show.html.erb
<%= render 'users/login_form' %>

<p>
  <strong>Title:</strong>
  <%= @advertisement.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @advertisement.content %>
</p>

<p>
  <strong>State:</strong>
  <%= @advertisement.state %>
</p>

<p>
  <strong>Price:</strong>
  <%= @advertisement.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @advertisement.user.name %>
</p>

<% if @current_user.try(:admin?) && @advertisement.state != 'published' %>
	<td><%= link_to 'Publish', @advertisement, method: :patch %></td> |
<% end %>
<% if @current_user.try(:admin?) %>
	<%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
<% end %>
<% if @current_user.try(:id) == @advertisement.user_id %>
  <%= link_to 'Edit', edit_advertisement_path(@advertisement) %> |
<% end %>

<%= link_to 'Back', advertisements_path %>

<hr>
<% if @current_user %>
	<h2>Leave a comment</h2>

	<%= form_tag "/advertisements/#{@advertisement.id}", method: :post do %>
		<%= text_area_tag(:content, "Hi !", id: :advertisement_content, size: "90x10") %>
		</br>
		<%= submit_tag('Comment') %>
		</br>
		<%= hidden_field :user_id, id: :comment_user_id %>
		<input type="hidden" name="advertisement_id" value="<%= @advertisement.id %>">
	<% end %>
<% end %>

<% if !@comments.length.zero? %>
	</br>
	<!-- </br> -->
	<h3>Comments</h3>
	<% @comments.each do |comment| %>
	<!-- alors là c'est bâtard... à partir de la liste des commentaires avec leur auteur-e respectif-ve, je sélectionne ceux dont l'id est identique à celui du commentaire en cours, et je ne garde que le nom -->
	<b><%# @comments_authors.select { |e| e.id == comment.id }.map(&:name)[0] %></b>
	<b><%= comment.user.name %></b>
	<p><%= comment.content %></p>
<% end %>
<% else %>
	<p>No comment</p>
<% end %>