RUBY/RAILS/activites/cours_2/activite_1/adlibitum/config/routes.rb
Rails.application.routes.draw do
  root 'advertisements#index'

  get 'advertisements/login' => 'users#login'
  patch 'advertisements/:id' => 'advertisements#publish'
  post 'advertisements/:id' => 'comments#create'
  post 'advertisements/login' => 'users#check'

  get 'users/login' => 'users#login'
  post 'users/login' => 'users#check'
  delete 'users' => 'users#logout'

  resources :comments
  resources :advertisements
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :advertisement
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  # def index
  #   @comments = Comment.all
  # end

  # GET /comments/1
  # GET /comments/1.json
  # def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  # def edit; end

  # POST /comments
  # POST /comments.json
  def create
    #  @comment = Comment.new(comment_params)
    @comment = Comment
    if @comment.create user_id: @current_user.id, content: params[:content], advertisement_id: params[:advertisement_id]
      redirect_to "/advertisements/#{params[:id]}"
    else
      render :show
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  # def update
  #   respond_to do |format|
  #     if @comment.update(comment_params)
  #       format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @comment }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @comment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /comments/1
  # DELETE /comments/1.json
  # def destroy
  #   @comment.destroy
  #   respond_to do |format|
  #     format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:title, :content, :user_id, :advertisement_id)
  end
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/helpers/comments_helper.rb
module CommentsHelper
end

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :comment_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field">
    <%= form.label :advertisement_id %>
    <%= form.text_field :advertisement_id, id: :comment_advertisement_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th>Advertisement</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= comment.user %></td>
        <td><%= comment.advertisement %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

RUBY/RAILS/activites/cours_2/activite_1/adlibitum/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_name[0].name %>
</p>

<p>
  <strong>Advertisement:</strong>
  <%= @comment.advertisement.title %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>